### ISSUE TITLE
Unable to place source in SUB64 FOV

### ISSUE THREAD

**Issue by taylorbell57** [STScI-MIRI/TSO-MIRI-simulations#5]
Hi Sarah,

I have been trying to use your MIRI simulation code to make some of my own custom MIRI simulations. I've successfully been able to produce LRS spectra and full-frame imaging mode observations, but when I try to use the SUB64 subarray using the "MIRI Imaging Time Series Observations simulations.ipynb" file I don't end up having any sources visible in the output FITS files. My guess is that this has something to do with the sub-arrays not being centered on the full-frame FOV, but my attempts at placing the star in the sub-array FOV using the offset positions from Section 7.7.1 of the [MIRISim documentation](https://wiki.miricle.org/pub/Public/MIRISimPublicRelease2dot3/MIRISim.pdf) have been unsuccessful. I have tried placing the point source at Cen=(-33.5*0.11,-809.5*0.11) and Cen=(33.5*0.11, 809.5*0.11) given the pixel displacements of [33.5, 809.5] pixels from the MIRISim documentation pdf and a pixel scale of 0.11 arcsec/pixel.

Any help you can provide would be much appreciated!

Cheers,
Taylor

**Comment by skendrew** [comment]
hi Taylor - ah yes, we've had this issue before. let me check how we solved it. can you just confirm to me what version of MIRISim you are using? thanks!

**Comment by skendrew** [comment]
actually I think I spotted it. in the main script for the imager TSO simulations I set the parameter `cfg` to IMA_FULL. I think this has to be set to IMA_SUB64 (or IMA_<subarray_name> generally for subarrays). In the datalabs_sim folder in the repository I have this set correctly for a subarray, but I never corrected it in the main script. Can you give that a try?

**Comment by taylorbell57** [comment]
Awesome, let me take a look - and I have mirisim version 2.4.0 FYI

**Comment by taylorbell57** [comment]
Aha, that was exactly the issue! Thanks so much!!

**Comment by skendrew** [comment]
excellent, thanks for confirming. I'll try to get that script updated so no one else encounters the same issue. If you want to chat more about working with MIRISim data for TSOs, drop me a line.
